<?php

use App\Models\ActionMaster;
use Illuminate\Database\Seeder;

class ActionMasterTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        ActionMaster::insert([
            [
                'group_num' => 1,
                'action_master_id' =>NULL,
                'action_name' => '判別',
                'val' => 1,
                'seq' => 1,
            ],
            [
                'group_num' => 1,
                'action_master_id' =>NULL,
                'action_name' => '潜在',
                'val' => 2,
                'seq' => 2,
            ],
            [
                'group_num' => 1,
                'action_master_id' =>NULL,
                'action_name' => '顕在',
                'val' => 3,
                'seq' => 3,
            ],
            [
                'group_num' => 1,
                'action_master_id' =>NULL,
                'action_name' => '媒介',
                'val' => 4,
                'seq' => 4,
            ],
            [
                'group_num' => 2,
                'action_master_id' =>1,
                'action_name' => 'TEL無',
                'val' => 1,
                'seq' => 1,
            ],
            [
                'group_num' => 2,
                'action_master_id' =>1,
                'action_name' => 'TEL有',
                'val' => 2,
                'seq' => 2,
            ],
            [
                'group_num' => 2,
                'action_master_id' =>1,
                'action_name' => '手段無',
                'val' => 3,
                'seq' => 3,
            ],
            [
                'group_num' => 3,
                'action_master_id' =>2,
                'action_name' => '短期',
                'val' => 1,
                'seq' => 1,
            ],
            [
                'group_num' => 3,
                'action_master_id' =>2,
                'action_name' => '長期',
                'val' => 2,
                'seq' => 2,
            ],
            [
                'group_num' => 3,
                'action_master_id' =>2,
                'action_name' => 'MA',
                'val' => 3,
                'seq' => 3,
            ],
            [
                'group_num' => 4,
                'action_master_id' =>3,
                'action_name' => '月内',
                'val' => 1,
                'seq' => 1,
            ],
            [
                'group_num' => 4,
                'action_master_id' =>3,
                'action_name' => '今期',
                'val' => 2,
                'seq' => 2,
            ],
            [
                'group_num' => 4,
                'action_master_id' =>3,
                'action_name' => '来期',
                'val' => 3,
                'seq' => 3,
            ],
            [
                'group_num' => 5,
                'action_master_id' =>4,
                'action_name' => '売主',
                'val' => 1,
                'seq' => 1,
            ],
            [
                'group_num' => 5,
                'action_master_id' =>4,
                'action_name' => '専任',
                'val' => 2,
                'seq' => 2,
            ],
            [
                'group_num' => 5,
                'action_master_id' =>4,
                'action_name' => '一般',
                'val' => 3,
                'seq' => 3,
            ],
            [
                'group_num' => 5,
                'action_master_id' =>4,
                'action_name' => '専属',
                'val' => 4,
                'seq' => 4,
            ],
            [
                'group_num' => 6,
                'action_master_id' =>NULL,
                'action_name' => 'エリア',
                'val' => 1,
                'seq' => 1,
            ],
            [
                'group_num' => 6,
                'action_master_id' =>NULL,
                'action_name' => '社内',
                'val' => 2,
                'seq' => 2,
            ],
            [
                'group_num' => 6,
                'action_master_id' =>NULL,
                'action_name' => '査定・商談',
                'val' => 3,
                'seq' => 3,
            ],
            [
                'group_num' => 6,
                'action_master_id' =>NULL,
                'action_name' => '会議・研修',
                'val' => 4,
                'seq' => 4,
            ],
            [
                'group_num' => 6,
                'action_master_id' =>NULL,
                'action_name' => '販売行動',
                'val' => 5,
                'seq' => 5,
            ],
            [
                'group_num' => 6,
                'action_master_id' =>NULL,
                'action_name' => 'その他',
                'val' => 6,
                'seq' => 6,
            ],
            [
                'group_num' => 7,
                'action_master_id' =>18,
                'action_name' => 'エリア1',
                'val' => 1,
                'seq' => 1,
            ],
            [
                'group_num' => 7,
                'action_master_id' =>18,
                'action_name' => 'エリア2',
                'val' => 2,
                'seq' => 2,
            ],
            [
                'group_num' => 7,
                'action_master_id' =>18,
                'action_name' => 'エリア3',
                'val' => 3,
                'seq' => 3,
            ],
            [
                'group_num' => 7,
                'action_master_id' =>18,
                'action_name' => 'エリア4',
                'val' => 4,
                'seq' => 4,
            ],
            [
                'group_num' => 7,
                'action_master_id' =>18,
                'action_name' => 'エリア5',
                'val' => 5,
                'seq' => 5,
            ],
            [
                'group_num' => 7,
                'action_master_id' =>18,
                'action_name' => 'エリア6',
                'val' => 6,
                'seq' => 6,
            ],
            [
                'group_num' => 7,
                'action_master_id' =>18,
                'action_name' => 'エリア7',
                'val' => 7,
                'seq' => 7,
            ],
            [
                'group_num' => 7,
                'action_master_id' =>18,
                'action_name' => 'エリア8',
                'val' => 8,
                'seq' => 8,
            ],
            [
                'group_num' => 17,
                'action_master_id' =>19,
                'action_name' => '仕入活動',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 17,
                'action_master_id' =>19,
                'action_name' => '事務作業',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 18,
                'action_master_id' =>20,
                'action_name' => 'web商談',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 18,
                'action_master_id' =>20,
                'action_name' => '査定・商談',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 18,
                'action_master_id' =>20,
                'action_name' => '再商談',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 19,
                'action_master_id' =>21,
                'action_name' => '社内会議',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 19,
                'action_master_id' =>21,
                'action_name' => '研修',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 20,
                'action_master_id' =>22,
                'action_name' => '販売行動',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 20,
                'action_master_id' =>22,
                'action_name' => '契約行動',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 20,
                'action_master_id' =>22,
                'action_name' => '決済行動',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 21,
                'action_master_id' =>23,
                'action_name' => 'その他',
                'val' => NULL,
                'seq' => NULL,
            ],

            [
                'group_num' => 8,
                'action_master_id' =>NULL,
                'action_name' => 'エリア発掘',
                'val' => 1,
                'seq' => 1,
            ],
            [
                'group_num' => 8,
                'action_master_id' =>NULL,
                'action_name' => '社内発掘',
                'val' => 2,
                'seq' => 2,
            ],
            [
                'group_num' => 8,
                'action_master_id' =>NULL,
                'action_name' => '反響',
                'val' => 3,
                'seq' => 3,
            ],
            [
                'group_num' => 8,
                'action_master_id' =>NULL,
                'action_name' => '前取関連',
                'val' => 4,
                'seq' => 4,
            ],
            [
                'group_num' => 8,
                'action_master_id' =>NULL,
                'action_name' => 'その他',
                'val' => 5,
                'seq' => 5,
            ],
            [
                'group_num' => 9,
                'action_master_id' =>43,
                'action_name' => '管理人訪問',
                'val' => 1,
                'seq' => 1,
            ],
            [
                'group_num' => 9,
                'action_master_id' =>43,
                'action_name' => '個人訪問',
                'val' => 2,
                'seq' => 2,
            ],
            [
                'group_num' => 9,
                'action_master_id' =>43,
                'action_name' => 'ポストチェック',
                'val' => 3,
                'seq' => 3,
            ],
            [
                'group_num' => 9,
                'action_master_id' =>43,
                'action_name' => '一棟チェック',
                'val' => 4,
                'seq' => 4,
            ],
            [
                'group_num' => 9,
                'action_master_id' =>43,
                'action_name' => '巡回現地情報',
                'val' => 5,
                'seq' => 5,
            ],
            [
                'group_num' => 9,
                'action_master_id' =>43,
                'action_name' => 'DM手まき反響',
                'val' => 6,
                'seq' => 6,
            ],
            [
                'group_num' => 9,
                'action_master_id' =>43,
                'action_name' => 'チラシ手まき反響',
                'val' => 7,
                'seq' => 7,
            ],
            [
                'group_num' => 9,
                'action_master_id' =>43,
                'action_name' => '手紙・封書手まき反響',
                'val' => 8,
                'seq' => 8,
            ],
            [
                'group_num' => 9,
                'action_master_id' =>43,
                'action_name' => 'ランダム戸別訪問',
                'val' => 9,
                'seq' => 9,
            ],
            [
                'group_num' => 10,
                'action_master_id' =>44,
                'action_name' => '管理人TEL',
                'val' => 1,
                'seq' => 1,
            ],
            [
                'group_num' => 10,
                'action_master_id' =>44,
                'action_name' => '個人TEL',
                'val' => 2,
                'seq' => 2,
            ],
            [
                'group_num' => 10,
                'action_master_id' =>44,
                'action_name' => 'ランダムTEL',
                'val' => 3,
                'seq' => 3,
            ],
            [
                'group_num' => 11,
                'action_master_id' =>44,
                'action_name' => 'DM郵送反響',
                'val' => 4,
                'seq' => 4,
            ],
            [
                'group_num' => 11,
                'action_master_id' =>44,
                'action_name' => '手紙・封書郵送反響',
                'val' => 5,
                'seq' => 5,
            ],
            [
                'group_num' => 12,
                'action_master_id' =>44,
                'action_name' => '売却チラシ宅配依頼反響',
                'val' => 6,
                'seq' => 6,
            ],
            [
                'group_num' => 12,
                'action_master_id' =>44,
                'action_name' => '郵送物戻り',
                'val' => 7,
                'seq' => 7,
            ],
            [
                'group_num' => 12,
                'action_master_id' =>44,
                'action_name' => '賃貸情報',
                'val' => 8,
                'seq' => 8,
            ],
            [
                'group_num' => 12,
                'action_master_id' =>44,
                'action_name' => '登記情報',
                'val' => 9,
                'seq' => 9,
            ],
            [
                'group_num' => 12,
                'action_master_id' =>44,
                'action_name' => '建築確認情報',
                'val' => 10,
                'seq' => 10,
            ],
            [
                'group_num' => 13,
                'action_master_id' =>45,
                'action_name' => '当社HP',
                'val' => 1,
                'seq' => 1,
            ],
            [
                'group_num' => 13,
                'action_master_id' =>45,
                'action_name' => '一括査定サイト',
                'val' => 2,
                'seq' => 2,
            ],
            [
                'group_num' => 13,
                'action_master_id' =>45,
                'action_name' => '他営業所紹介',
                'val' => 3,
                'seq' => 3,
            ],
            [
                'group_num' => 13,
                'action_master_id' =>45,
                'action_name' => '本社・グループ会社紹介',
                'val' => 4,
                'seq' => 4,
            ],
            [
                'group_num' => 14,
                'action_master_id' =>46,
                'action_name' => '前取訪問',
                'val' => 1,
                'seq' => 1,
            ],
            [
                'group_num' => 14,
                'action_master_id' =>46,
                'action_name' => '前取TEL',
                'val' => 2,
                'seq' => 2,
            ],
            [
                'group_num' => 14,
                'action_master_id' =>46,
                'action_name' => '前取自己発見',
                'val' => 3,
                'seq' => 3,
            ],
            [
                'group_num' => 14,
                'action_master_id' =>46,
                'action_name' => '前取反響',
                'val' => 4,
                'seq' => 4,
            ],
            [
                'group_num' => 14,
                'action_master_id' =>46,
                'action_name' => '前取その他',
                'val' => 5,
                'seq' => 5,
            ],
            [
                'group_num' => 15,
                'action_master_id' =>47,
                'action_name' => '業者関与',
                'val' => 1,
                'seq' => 1,
            ],
            [
                'group_num' => 15,
                'action_master_id' =>47,
                'action_name' => 'オープンルーム',
                'val' => 2,
                'seq' => 2,
            ],
            [
                'group_num' => 15,
                'action_master_id' =>47,
                'action_name' => 'フリー来社',
                'val' => 3,
                'seq' => 3,
            ],
            [
                'group_num' => 15,
                'action_master_id' =>47,
                'action_name' => 'その他',
                'val' => 4,
                'seq' => 4,
            ],
            [
                'group_num' => 16,
                'action_master_id' =>NULL,
                'action_name' => '自己居住',
                'val' => 1,
                'seq' => 1,
            ],
            [
                'group_num' => 16,
                'action_master_id' =>NULL,
                'action_name' => '空室',
                'val' => 2,
                'seq' => 2,
            ],
            [
                'group_num' => 16,
                'action_master_id' =>NULL,
                'action_name' => '賃貸',
                'val' => 3,
                'seq' => 3,
            ],
            [
                'group_num' => 16,
                'action_master_id' =>NULL,
                'action_name' => '家族居住',
                'val' => 4,
                'seq' => 4,
            ],
            [
                'group_num' => 16,
                'action_master_id' =>NULL,
                'action_name' => 'セカンド',
                'val' => 5,
                'seq' => 5,
            ],
            [
                'group_num' => 16,
                'action_master_id' =>NULL,
                'action_name' => '社宅',
                'val' => 6,
                'seq' => 6,
            ],
            [
                'group_num' => 16,
                'action_master_id' =>NULL,
                'action_name' => '店舗・hat所',
                'val' => 7,
                'seq' => 7,
            ],
            [
                'group_num' => 16,
                'action_master_id' =>NULL,
                'action_name' => 'その他',
                'val' => 8,
                'seq' => 8,
            ],
            [
                'group_num' => 23,
                'action_master_id' =>NULL,
                'action_name' => 'サイトA',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 23,
                'action_master_id' =>NULL,
                'action_name' => 'サイトB',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 23,
                'action_master_id' =>NULL,
                'action_name' => 'サイトC',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 23,
                'action_master_id' =>NULL,
                'action_name' => 'サイトD',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 23,
                'action_master_id' =>NULL,
                'action_name' => 'サイトE',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 23,
                'action_master_id' =>NULL,
                'action_name' => 'サイトF',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 23,
                'action_master_id' =>NULL,
                'action_name' => 'サイトG',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 23,
                'action_master_id' =>NULL,
                'action_name' => 'サイトH',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 23,
                'action_master_id' =>NULL,
                'action_name' => 'サイトI',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 23,
                'action_master_id' =>NULL,
                'action_name' => 'サイトJ',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 23,
                'action_master_id' =>NULL,
                'action_name' => 'サイトK',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 23,
                'action_master_id' =>NULL,
                'action_name' => 'サイトN',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 23,
                'action_master_id' =>NULL,
                'action_name' => 'サイトM',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 23,
                'action_master_id' =>NULL,
                'action_name' => 'サイトL',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 23,
                'action_master_id' =>NULL,
                'action_name' => 'サイトO',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 1,
                'action_master_id' =>NULL,
                'action_name' => '発掘降格',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 22,
                'action_master_id' =>NULL,
                'action_name' => '発掘降格',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 7,
                'action_master_id' =>18,
                'action_name' => 'エリア9',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 7,
                'action_master_id' =>18,
                'action_name' => 'エリア10',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 7,
                'action_master_id' =>18,
                'action_name' => 'エリア11',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 7,
                'action_master_id' =>18,
                'action_name' => 'エリア12',
                'val' => NULL,
                'seq' => NULL,
            ],
            [
                'group_num' => 23,
                'action_master_id' =>NULL,
                'action_name' => 'その他',
                'val' => NULL,
                'seq' => NULL,
            ],
        ]);
    }
}
